### ISSUE TITLE
Japanese translation has not been updated since 2022-08-01

### ISSUE THREAD

**Issue by methane** [python/docsbuild-scripts#142]
https://docs.python.org/ja/3.11/index.html is updated at 2022-08-01.

Recently, I updated python/python-docs-ja but docs.python.org are not updated.
I ran docsbuild-scripts locally and confirmed that Japanese document can be built successfully.

What's going on docs.python.org? Can I see build log in the server?

**Comment by egeakman** [comment]
I can see the changes from https://github.com/python/python-docs-ja/commit/cbf155e9e0487fd71039d32d076999bd60176311 on docs.python.org, showing that it is working fine. Since the server builds the translations daily, you probably have to wait until then.

**Comment by souma987** [comment]
I don't think the Japanese translations are up to date on docs.python.org.

For example, a typo is still on https://docs.python.org/ja/3.11/library/xml.etree.elementtree.html but it is already fixed in python/python-docs-ja@3d5da943276b45483dd95ed1b4661cff5c66c04f .

On docs.python.org, in the red box, "データ**をを**パースする" is a typo of "データ**を**パースする" .

The typo is fixed at line58 and 59 of library/xml.etree.elementtree.po.

In addition, in the bottom right corner of the Japanese translations on docs.python.org, it says "最終更新: 8月 01, 2022 Found a bug?" which means "last updated on Aug 1, 2022" which shows the translation is not up to date.

**Comment by JulienPalard** [comment]
It may be related to https://github.com/python/python-docs-ja/issues/35: as the build is failing the script maybe does not rsync the HTML?

**Comment by methane** [comment]
Using Japanese in latex is difficult topic and I don't have any knowledge about latex. I never used latex.
So I can not fix the issue soon.

Please update HTML without PDF.

**Comment by JulienPalard** [comment]
> Please update HTML without PDF.

Done. I see "2023" on `/ja/` :)

**Comment by methane** [comment]
Thank you.
