### ISSUE TITLE
Translations do not redirect to 3.12

### ISSUE THREAD

**Issue by egeakman** [python/docsbuild-scripts#166]
Translations (`docs.python.org/xx/3/`) redirects to the 3.11 docs, while English (`docs.python.org/3/`) redirects to 3.12.

`Version.current_stable().name` shows 3.12 when I try locally, so will the redirections work properly after a rebuild or is there something wrong?

If this is something normal, sorry for the noob bug report/question, this is only the second time I'm witnessing a major update, while working on the documentation itself.

**Comment by AA-Turner** [comment]
cc @ambv (as he fixed the ``/3/`` symlink)

A

**Comment by JulienPalard** [comment]
This is due to old build runners still being alive with the old configuration.

It should be fixed by https://github.com/python/docsbuild-scripts/pull/168

I manually killed all old scripts and I'm manually starting a:

    /srv/docsbuild/venv/bin/python /srv/docsbuild/scripts/build_docs.py --quick

so we at least get links right, "quickly".

But still it means that we hit the spot: builds take now more than 24h.

**Comment by egeakman** [comment]
Fixed for now, but we should definitely look into getting builds faster.
