### ISSUE TITLE
Dev docs not updating

### ISSUE THREAD

**Issue by hugovk** [python/docsbuild-scripts#173]
https://docs.python.org/dev was last updated on Oct 19, 2023.

(https://docs.python.org/3/ is ok, last updated on Oct 21, 2023.)

@JulienPalard Please can you check it? Are the build logs visible somewhere?

**Comment by JulienPalard** [comment]
> Please can you check it? 

This is due to https://github.com/python/docsbuild-scripts/issues/169, when a full build takes more than 24h, the next build is skipped (it cannot start as the previous is not complete). Leading to a build every other day.

> Are the build logs visible somewhere?

The build logs are in `/var/log/docsbuild/docsbuild.log` on docs.nyc1.psf.io.

But a few PRs has been merged recently: 

- https://github.com/python/docsbuild-scripts/pull/143
- https://github.com/python/docsbuild-scripts/pull/171

so since yesterday I'm running the script manually to keep a close eye on it, so the file logs are empty, #sry, I read on stdout.

But but but according to what I see, https://docs.python.org/dev/ has been built today \o/

And with the recently merged PRs (rebuilding only if needed) I hope to see more than daily builds soon.

I may also prioritize english and dev while building if you want, so /dev/ gets updated "quickly", let's follow up on #169 as needed.

**Comment by hugovk** [comment]
Thanks! And good work with #171 :)

> The build logs are in `/var/log/docsbuild/docsbuild.log` on docs.nyc1.psf.io.

I guess this isn't publicly visible. Could it be uploaded somewhere?
